name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  mix_test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['23', '24', '25']
        elixir: ['1.11', '1.12','1.13', '1.14']
        exclude:
          - elixir: "1.11"
            otp: "24"
          - elixir: "1.11"
            otp: "25"
          - elixir: "1.12"
            otp: "25"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Configure git with fake data
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Install Dependencies
        run: mix deps.get
      - name: Check Formatted
        run: mix format --check-formatted
      - name: Run Tests
        run: mix test
